### ISSUE TITLE
I have an error in ubuntu 16.04

### ISSUE THREAD

**Issue by mrmrn** [nikhilkumarsingh/Wit-Speech-API-Wrapper#1]
hi.
I installed all packages and run your code.it can recognize my voice and when my voice is stopped but give me an error. here is the terminal log:
```

reka@marn ~/s/Wit-Speech-API-Wrapper> python speech_to_text.py
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Listening...
Finished recording.
Traceback (most recent call last):
  File "speech_to_text.py", line 39, in <module>
    text =  RecognizeSpeech('myspeech.wav', 4)
  File "speech_to_text.py", line 32, in RecognizeSpeech
    text = data['_text']
KeyError: '_text'
reka@marn ~/s/Wit-Speech-API-Wrapper> 

```

**Comment by nikhilkumarsingh** [comment]
It seems the HTTP response object doesn't have "_text" key. Can you please just print **data** dictionary?
It seems to be an issue with Wit Speech API.

**Comment by mrmrn** [comment]
yeah, you are right.
It was the access token problem.
now it works like a charm but have some problems I will ask you in another issues.
thank you for your fast response.

**Comment by hassanikram** [comment]
File "speech_to_text.py", line 39, in <module>
    text =  RecognizeSpeech('myspeech.wav', 4)
  File "speech_to_text.py", line 32, in RecognizeSpeech
    text = data['_text']
KeyError: '_text'

I'm getting this error can you please help?
