### ISSUE TITLE
does the time of speech is limited?

### ISSUE THREAD

**Issue by mrmrn** [nikhilkumarsingh/Wit-Speech-API-Wrapper#3]
does the time of speech is limited? or can it suggest the end of speech?
or can I feed it by my own .wave sound file?
thanks.

**Comment by nikhilkumarsingh** [comment]
Wit speech API doesn't mention any limits on input audio size.
You can pass your desired recording time simply by passing number of seconds to RecognizeSpeech function.
https://github.com/nikhilkumarsingh/Wit-Speech-API-Wrapper/blob/master/speech_to_text.py#L12

**Comment by nikhilkumarsingh** [comment]
You can pass your own wav sound file.
Just comment out this line:
https://github.com/nikhilkumarsingh/Wit-Speech-API-Wrapper/blob/master/speech_to_text.py#L15

**Comment by mrmrn** [comment]
thank you.
